/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vistas;

/**
 *
 * @author crisa
 */
public class Repo_Antropo extends javax.swing.JPanel {

    /**
     * Creates new form Repo_Antropo
     */
    public Repo_Antropo() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lb_idPaciente = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        lb_idRack = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jSeparator1 = new javax.swing.JSeparator();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        idPaciente = new javax.swing.JLabel();
        Busca_Paciente = new javax.swing.JTextField();
        Bttn_Buscar = new javax.swing.JButton();
        bttn_Avanzado = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();

        setBackground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(1180, 500));
        setLayout(new java.awt.BorderLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Datos del Paciente"));

        lb_idPaciente.setText("IdPaciente: ");
        jPanel1.add(lb_idPaciente);

        jTextField1.setColumns(15);
        jPanel1.add(jTextField1);

        lb_idRack.setText("No. Rack: ");
        jPanel1.add(lb_idRack);

        jTextField2.setColumns(15);
        jPanel1.add(jTextField2);

        jLabel3.setText("Fecha de seguimientos: ");
        jPanel1.add(jLabel3);

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "16/02/2018", "17/02/2018", "18/02/2018", "19/02/2018", "20/02/2018" }));
        jComboBox1.setPreferredSize(new java.awt.Dimension(100, 22));
        jPanel1.add(jComboBox1);

        add(jPanel1, java.awt.BorderLayout.NORTH);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Evaluacion Antropometrica"));
        jPanel2.setLayout(new javax.swing.BoxLayout(jPanel2, javax.swing.BoxLayout.PAGE_AXIS));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null}
            },
            new String [] {
                "Peso", "Estatura", "Edad"
            }
        ));
        jTable1.setPreferredSize(new java.awt.Dimension(125, 16));
        jScrollPane1.setViewportView(jTable1);

        jPanel2.add(jScrollPane1);

        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jSeparator1.setPreferredSize(new java.awt.Dimension(50, 30));
        jPanel2.add(jSeparator1);

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Kilos Grasa", "% Agua", "Kg. Musculo", "Espalda", "Brazo", "Cintura Alta", "Abdomen", "Cadera", "Pierna", "Edad Metabolica"
            }
        ));
        jScrollPane2.setViewportView(jTable2);

        jPanel2.add(jScrollPane2);

        add(jPanel2, java.awt.BorderLayout.CENTER);

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setPreferredSize(new java.awt.Dimension(100, 40));
        jPanel3.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.RIGHT));

        jButton1.setText("Guardar");
        jButton1.setPreferredSize(new java.awt.Dimension(120, 25));
        jPanel3.add(jButton1);

        jButton2.setText("Cancelar");
        jButton2.setPreferredSize(new java.awt.Dimension(120, 25));
        jPanel3.add(jButton2);

        add(jPanel3, java.awt.BorderLayout.SOUTH);

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder("Busqueda:"));
        jPanel4.setPreferredSize(new java.awt.Dimension(180, 200));

        idPaciente.setText("Id Paciente");
        jPanel4.add(idPaciente);

        Busca_Paciente.setColumns(15);
        Busca_Paciente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Busca_PacienteActionPerformed(evt);
            }
        });
        jPanel4.add(Busca_Paciente);

        Bttn_Buscar.setText("Buscar");
        jPanel4.add(Bttn_Buscar);

        bttn_Avanzado.setText("Busqueda Avanzada");
        jPanel4.add(bttn_Avanzado);

        add(jPanel4, java.awt.BorderLayout.WEST);

        jPanel5.setLayout(new javax.swing.BoxLayout(jPanel5, javax.swing.BoxLayout.Y_AXIS));
        add(jPanel5, java.awt.BorderLayout.EAST);
    }// </editor-fold>//GEN-END:initComponents

    private void Busca_PacienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Busca_PacienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Busca_PacienteActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Bttn_Buscar;
    private javax.swing.JTextField Busca_Paciente;
    private javax.swing.JButton bttn_Avanzado;
    private javax.swing.JLabel idPaciente;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JLabel lb_idPaciente;
    private javax.swing.JLabel lb_idRack;
    // End of variables declaration//GEN-END:variables
}
